# Generated by Django 5.1.1 on 2024-10-11 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topics',
        ),
    ]
